home:
    path: /
    controller: App\Controller\DefaultController::indexAction

admin:
    path: /admin/
    controller: App\Controller\AdminController::indexAction

cat:
    path: /admin/cat
    controller: App\Controller\AdminController::catAction

editcat:
    path: /admin/editcat/{id}/update
    controller: App\Controller\EditAdmin::catAction

tech:
    path: /admin/tech
    controller: App\Controller\AdminController::techAction

edittech:
    path: /admin/edittech/{id}/update
    controller: App\Controller\EditAdmin::techAction

skills:
    path: /admin/skills
    controller: App\Controller\AdminController::skillsAction

editskill:
    path: /admin/editskill/{id}/update
    controller: App\Controller\EditAdmin::skillsAction

projects:
    path: /admin/projects
    controller: App\Controller\AdminController::projectsAction

editproject:
    path: /admin/editproject/{id}/update
    controller: App\Controller\EditAdmin::projectsAction

delete:
    path: /admin/delete/{repository}/{id}/{redirect}
    controller: App\Controller\EditAdmin::delete